# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+title: README.org

#+STARTUP: overview indent

* Introduction
This repository is focused on running OpenMX calculations and extracting the
real-space Hamiltonian.



* Setup

** Installation

*** Obtain the Code from GitHub
The first step is to obtain this repository from GitHub. On Kodiak,
navigate to a location where you want to clone the code. Then, use
#+begin_src sh :eval never
  git clone https://github.com/enriquepacis/kodiak-openmx.git
#+end_src

*** Create, activate, and configure a Python Virtual Environment
I created this repository for use with the ~Python 3.12.8~ available
on Kodiak.
1. Use ~module load python/3.12.8~ either explicitly or in your
   ~./bashrc~ to use the recommended version of Python.
2. Create the ~venv~ using a customized version of
   #+begin_src sh :eval never
     python -m venv /path/to/venv/my-env-name
   #+end_src
3. Activate your new virtual environment using
   #+begin_src sh :eval never
     source /path/to/venv/my-env-name/bin/activate
   #+end_src
4. Use
   #+begin_src sh :eval never
     pip install -e .
   #+end_src
   to install the dependencies and the custom ~openmx_tools~ package.

*** Link the ~/data/...~ Storage Path to Your

We want to minimize the data we store in our
~/ion/home/your_username/~ path, since it is quite limited. However,
there is a larger, longer-term storage path,
~/data/your_username/~. Suppose we have
~/ion/home/your_username/.../kodiak-openmx~ as a clone of the repo,
and we have prepared ~/data/your_username/openmx-storage~ as a
long-term storage directory we created for our calculations. Then,
within ~kodiak-openmx~, we can create ~calcs~ as a symbolic link
to the longer-term storage. In the
~kodiak-openmx~ directory, use something like
#+begin_src sh :eval never
  # structure: ln -s /path/to/storage-dir sym-link
  ln -s /data/your_username/openmx-storage calcs
#+end_src

To verify the creation of a symbolic link, we can use ~ls -lt~ in the
~kodiak-openmx~ directory. Mine looks like this:
#+begin_src sh :eval never
  $ ls -lt
  total 518
  lrwxrwxrwx 1 blaire blaire   26 May 23 17:30  calcs -> /data/blaire/kodiak-openmx
  -rw-r--r-- 1 blaire blaire 4181 May 23 17:30 '#README.org#'
  drwxr-xr-x 2 blaire blaire  512 May 23 16:39  dev
  drwxr-xr-x 4 blaire blaire  512 May 23 16:29  src
  -rw-r--r-- 1 blaire blaire  280 May 23 16:28  pyproject.toml
  -rw-r--r-- 1 blaire blaire  118 May 23 16:28  environment.yml
  drwxr-xr-x 4 blaire blaire  512 May 23 16:12  notebooks
  -rw-r--r-- 1 blaire blaire 2481 May 23 13:33  README.org
#+end_src
The entry for ~calcs~ is at the top, and it is indicated as a symbolic
link by the first character ~l~ on that line, along with the ~->~
indicating the path it links to.

Now, within ~openmx-, we can treat ~calcs~ like a directory, but
anything we do to ~calcs~ is actually done to the storage path it
links to.

** Tunneling into Kodiak for Jupyter Service

*** Start a Jupyter Lab server

1. Login on kodiak from a local terminal using something like, but customizing
   ~your_username~ with a value appropriate to you:
   #+begin_src zsh :eval never
     ssh your_username@kodiak.baylor.edu
   #+end_src
2. Establish an interactive session on a compute node:
   #+begin_src zsh :eval never
     qsub -I -q batch
   #+end_src
   This gets us one core on one compute node on the batch queue.
3. Find the hostname for the compute node we're using:
   #+begin_src zsh :eval never :results output
     hostname
   #+end_src
   For example, I may use ~hostname~ and see this:
   #+begin_src zsh :results output :eval never
     $ hostname
     n024
   #+end_src
   Thus, the node is ~n024~.
4. Activate the desired Python environment.
   This environment must have ~jupyterlab~ installed.
5. Start Jupyter (headless)
   #+begin_src zsh :results output
     jupyter lab --no-browser --ip=0.0.0.0 --port=8887
   #+end_src
   I'm suggesting that we use a specific (non-default) port number (default
   is 8888) so that we have a distinct Jupyter Lab from the default that may be
   running locally (this likely won't matter).

   The use of ~--ip=0.0.0.0~ allows the login node to "see" port 8887 of the
   compute node.

   The above command should include in its output information like this:
   #+begin_quote
       To access the server, open this file in a browser:
        file:///ion/home/your_username/.local/share/jupyter/runtime/jpserver-1281948-open.html
    Or copy and paste one of these URLs:
        http://localhost:8887/lab?token=58ff72ece4f31b1858834096f0dfb92d8897139c0e729438
        http://127.0.0.1:8887/lab?token=58ff72ece4f31b1858834096f0dfb92d8897139c0e729438
   #+end_quote
   From this, we save the token. In this example, it's ~58ff72ece4f31b1858834096f0dfb92d8897139c0e729438~
6. Tunnel from your laptop or local computer
   #+begin_src zsh :eval never
     ssh -L 8887:n024:8887 blaire@kodiak.baylor.edu
   #+end_src

   This maps local port 8887 of my laptop to port 8887 of n024 on Kodiak.
7. Point a browser to:
   #+begin_quote
   http://localhost:8887/lab?token=YOUR_TOKEN
   #+end_quote
   where ~YOUR_TOKEN~ is the token we saved earlier.


