# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+title: README.org

#+STARTUP: overview indent

* Introduction
This repository is focused on running OpenMX calculations and extracting the
real-space Hamiltonian.


* Basis Functions

** Pseudo-atomic Orbitals (PAOs)

OpenMX uses localized atomic-like basis functions called pseudo-atomic orbitals
(PAOs). Each basis function is $\phi_{i\alpha}(\mathbf{r})$ is a numerical
atomic orbital centered on atom \(i\). The angular part of \(\phi_{i\alpha}\) is
defined by spherical harmonics, and the radial part is the numerical solution of
the atomic problem.

For example, we may use ~H5.0-s2p1~, where
- a cutoff radius of 5.0 Bohr is specified for hydrogen,
- 2 radial functions are used for the s orbital
- 1 radial function is used for p orbitals
Here, we will expect 2 s orbitals and one orbital each for the px, py, and pz
orbitals, for a total of 5 orbitals as basis functions.

For a system of two H atoms, we might conceptualize the real-space Hamiltonian
elements as \(H_{i\alpha,j\beta}\), which is the transition energy between
oribtal \(\beta\) on the \(j\)-atom. For Python, we flatten \(i\alpha\) to an
integer index using something like this:
#+begin_src python :eval never
  i0 = self.orbital_offset[ct_AN]
  j0 = self.orbital_offset[Gh_AN]

  rows.append(i0 + i)
  cols.append(j0 + j)
#+end_src
Here,
- ~ct_AN~ maps to atom index \(i\),
- ~i~ is orbital index \(\alpha\),
- ~Gh_AN~ maps to atom index \(j\)
- ~j~ is orbital index \(\beta\),


** Structure of the Basis

OpenMX uses atom-major ordering, then orbital ordering, with index \(\nu = (i,
\alpha)\), where
- \(i\) indexes atoms, and
- \(\alpha\) indexes an orbital on that atom

- What is the atomic problem?
- Break down for me further what it means to use multiple radial functions for
  an s orbital
- What does it look like to use multiple 

* Gauge Convention

* Setup


** Tunneling into Kodiak for Jupyter Service

*** Start a Jupyter Lab server

1. Login on kodiak from a local terminal using something like, but customizing
   ~your_username~ with a value appropriate to you:
   #+begin_src zsh :eval never
     ssh your_username@kodiak.baylor.edu
   #+end_src
2. Establish an interactive session on a compute node:
   #+begin_src zsh :eval never
     qsub -I -q batch
   #+end_src
   This gets us one core on one compute node on the batch queue.
3. Find the hostname for the compute node we're using:
   #+begin_src zsh :eval never :results output
     hostname
   #+end_src
   For example, I may use ~hostname~ and see this:
   #+begin_src zsh :results output :eval never
     $ hostname
     n024
   #+end_src
   Thus, the node is ~n024~.
4. Activate the desired Python environment.
   This environment must have ~jupyterlab~ installed.
5. Start Jupyter (headless)
   #+begin_src zsh :results output
     jupyter lab --no-browser --ip=0.0.0.0 --port=8887
   #+end_src
   I'm suggesting that we use a specific (non-default) port number (default
   is 8888) so that we have a distinct Jupyter Lab from the default that may be
   running locally (this likely won't matter).

   The use of ~--ip=0.0.0.0~ allows the login node to "see" port 8887 of the
   compute node.

   The above command should include in its output information like this:
   #+begin_quote
       To access the server, open this file in a browser:
        file:///ion/home/your_username/.local/share/jupyter/runtime/jpserver-1281948-open.html
    Or copy and paste one of these URLs:
        http://localhost:8887/lab?token=58ff72ece4f31b1858834096f0dfb92d8897139c0e729438
        http://127.0.0.1:8887/lab?token=58ff72ece4f31b1858834096f0dfb92d8897139c0e729438
   #+end_quote
   From this, we save the token. In this example, it's ~58ff72ece4f31b1858834096f0dfb92d8897139c0e729438~
6. Tunnel from your laptop or local computer
   #+begin_src zsh :eval never
     ssh -L 8887:n024:8887 blaire@kodiak.baylor.edu
   #+end_src

   This maps local port 8887 of my laptop to port 8887 of n024 on Kodiak.
7. Point a browser to:
   #+begin_quote
   http://localhost:8887/lab?token=YOUR_TOKEN
   #+end_quote
   where ~YOUR_TOKEN~ is the token we saved earlier.


